services:
  wiki_updates:
    image: wiki_updates
    build: .
    ports:
      - "80:80"
    depends_on:
      database-init:
        condition: service_completed_successfully
    networks:
      - wiki

  database:
    image: cassandra:latest
    container_name: database
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=database
    healthcheck:
        test: ["CMD-SHELL", "nodetool status"]
        interval: 30s
        timeout: 10s
        retries: 5
    volumes:
      - ./database-data:/var/lib/cassandra
    networks:
      - wiki

  database-init:
    image: cassandra:latest
    depends_on:
      database:
        condition: service_healthy
    restart: "no"
    entrypoint: ["/init.sh", "database"]
    volumes:
      - ./data/scripts/init.sh:/init.sh
    networks:
      - wiki

networks:
  wiki:
    driver: bridge
