name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.25.1

    services:
      database:
        image: cassandra:latest
        ports:
          - 9042:9042
        options: >-
          --health-cmd="nodetool status"
          --health-interval=30s
          --health-timeout=10s
          --health-retries=5
        env:
          CASSANDRA_BROADCAST_ADDRESS: database

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install libev-dev
        run: |
          sudo apt update
          sudo apt install -y libev-dev

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use a compatible Python version (3.6+ generally)

      - name: Install cqlsh
        run: python3 -m pip install cqlsh


      - name: Install dependencies
        run: go mod download

      - name: Init Database
        run: ./data/scripts/init.sh database

      - name: Run tests
        run: go test -v ./...

